# The name of your workflow. This is what you'll see in the GitHub Actions tab.
name: End-to-End Tests

# This section defines WHEN the pipeline should run.
on:
  # Run it on every 'push' to the main branch.
  push:
    branches: [ main ]
  # Also run it on every 'pull request' that targets the main branch.
  pull_request:
    branches: [ main ]

# This section defines the TASKS (or "jobs") the pipeline will perform.
jobs:
  # We are defining a single job called "run-tests".
  run-tests:
    # This specifies the virtual machine to run on. "ubuntu-latest" is a standard, reliable choice.
    runs-on: ubuntu-latest

    # This section lists the individual steps the job will take, in order.
    steps:
      # Step 1: Check out your code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment for Cypress
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js to use

      # Step 3: Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # Step 4: Set up Python environment for Robot Framework
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the version of Python to use

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary

      # Step 6: Run the Cypress Test Suite
      - name: Run Cypress Tests
        run: npm run test:cypress
        continue-on-error: true

      # This step uploads the HTML report artifact
      - name: Upload Cypress Test Report   # <--- CORRECTED INDENTATION
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-report
          path: cypress/reports/html

      # This step uploads screenshots ONLY if tests failed
      - name: Upload Cypress Screenshots on Failure # <--- CORRECTED INDENTATION
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Step 7: Run the Robot Framework Test Suite
      - name: Run Robot Framework Tests
        run: npm run test:robot
        continue-on-error: true
